from typing import Protocol, Callable, Dict

class PubSub(Protocol):
    def publish_json(self, topic: str, obj: dict, *, qos: int = 0, retain: bool = False) -> None: ...
    def subscribe_prefix(self, prefix: str, handler: Callable[[str, dict], None]) -> None: ...

class RpcClient(Protocol):
    def rpc(self, request_topic: str, payload: dict, timeout: float = 5.0) -> dict: ...
